<template>
  <div>
    <el-table
      class="transaction-table"
      :data="transactions"
    >
      <el-table-column prop="id" label="id" width="40"></el-table-column>
      <el-table-column prop="from" label="from"></el-table-column>
      <el-table-column prop="to" label="to"></el-table-column>
      <el-table-column prop="amount" label="amount"></el-table-column>
      <el-table-column prop="date" label="date"></el-table-column>
    </el-table>
  </div>
</template>

<script>
  import _ from 'lodash'
  import moment from 'moment'

  /**
   * Renderes transactions, associated with a walletId, on a table.
   */
  export default {
    name: 'transactions',

    props: {
      walletId: String
    },

    data () {
      return {
        transactions: []
      }
    },

    created () {
      this.fetchTransactionsByWalletId(this.walletId)
    },

    watch: {
      walletId (to, from) {
        this.fetchTransactionsByWalletId(this.walletId)
      }
    },

    methods: {
      /**
       * TODO: This is dummy and transactions are hardcoded for now.
       * I guess it will be replaced with API call to fetch transactions by walletId
       * and will perform dispatching an action to a store or the like.
       * The dummy data was generated by https://mockaroo.com/
       */
      fetchTransactionsByWalletId (walletId) {
        this.transactions = _([
          { 'id': 1, 'from': 'che@russia', 'to': 'you', 'amount': 498.36, 'date': '2017-12-05T00:33:23Z' },
          { 'id': 2, 'from': 'armstrong@russia', 'to': 'you', 'amount': 162.18, 'date': '2017-04-24T01:52:54Z' },
          { 'id': 3, 'from': 'lauri@russia', 'to': 'you', 'amount': 95.99, 'date': '2017-07-07T05:21:39Z' },
          { 'id': 4, 'from': 'jude@russia', 'to': 'you', 'amount': 81.92, 'date': '2017-05-19T14:50:02Z' },
          { 'id': 5, 'from': 'barbara@russia', 'to': 'you', 'amount': 192.45, 'date': '2017-11-15T17:30:57Z' },
          { 'id': 6, 'from': 'monro@russia', 'to': 'you', 'amount': 283.36, 'date': '2017-06-07T18:27:16Z' },
          { 'id': 7, 'from': 'reider@russia', 'to': 'you', 'amount': 433.22, 'date': '2017-10-22T06:21:30Z' },
          { 'id': 8, 'from': 'marthe@russia', 'to': 'you', 'amount': 76.22, 'date': '2017-10-23T17:59:33Z' },
          { 'id': 9, 'from': 'joellen@russia', 'to': 'you', 'amount': 123.72, 'date': '2018-04-15T19:59:50Z' },
          { 'id': 10, 'from': 'benedicta@russia', 'to': 'you', 'amount': 51.19, 'date': '2017-11-21T09:54:43Z' },
          { 'id': 11, 'from': 'gardener@russia', 'to': 'you', 'amount': 154.6, 'date': '2018-04-19T14:04:05Z' },
          { 'id': 12, 'from': 'nobie@russia', 'to': 'you', 'amount': 160.72, 'date': '2017-10-28T17:05:31Z' },
          { 'id': 13, 'from': 'elfrieda@russia', 'to': 'you', 'amount': 146.48, 'date': '2018-03-30T04:22:03Z' },
          { 'id': 14, 'from': 'marisa@russia', 'to': 'you', 'amount': 86.15, 'date': '2018-02-10T05:13:49Z' },
          { 'id': 15, 'from': 'welch@russia', 'to': 'you', 'amount': 71.64, 'date': '2017-11-06T06:53:03Z' },
          { 'id': 16, 'from': 'wendi@russia', 'to': 'you', 'amount': 101.45, 'date': '2017-06-03T16:45:11Z' },
          { 'id': 17, 'from': 'sigismondo@russia', 'to': 'you', 'amount': 415.67, 'date': '2017-11-08T13:15:59Z' },
          { 'id': 18, 'from': 'seamus@russia', 'to': 'you', 'amount': 261.06, 'date': '2017-05-06T15:56:47Z' },
          { 'id': 19, 'from': 'cyrillus@russia', 'to': 'you', 'amount': 460.26, 'date': '2017-11-21T22:56:36Z' },
          { 'id': 20, 'from': 'adina@russia', 'to': 'you', 'amount': 84.58, 'date': '2017-05-07T03:21:06Z' }
        ])
          .chain()
          .sampleSize(_.random(3, 20))
          .map((d) => {
            d.date = moment(d.date).format('DD.MM.YYYY')
            return d
          })
          .value()
      }
    }
  }
</script>

<style lang="scss" scoped>
  @import "~@/styles/element-variables.scss";
</style>
