<template>
  <div>
    <el-table
      class="transaction-table"
      :data="transactions"
    >
      <el-table-column prop="id" label="id"></el-table-column>
      <el-table-column prop="from" label="from"></el-table-column>
      <el-table-column prop="to" label="to"></el-table-column>
      <el-table-column prop="amount" label="amount"></el-table-column>
      <el-table-column prop="date" label="date"></el-table-column>
    </el-table>
  </div>
</template>

<script>
  import _ from 'lodash'
  import moment from 'moment'

  /**
   * Renderes transactions, associated with a walletId, on a table.
   */
  export default {
    name: 'transactions',

    props: {
      walletId: String
    },

    data () {
      return {
        transactions: []
      }
    },

    created () {
      this.fetchTransactionsByWalletId(this.walletId)
    },

    watch: {
      walletId (to, from) {
        this.fetchTransactionsByWalletId(this.walletId)
      }
    },

    methods: {
      /**
       * TODO: This is dummy and transactions are hardcoded for now.
       * I guess it will be replaced with API call to fetch transactions by walletId
       * and will perform dispatching an action to a store or the like.
       * The dummy data was generated by https://mockaroo.com/
       */
      fetchTransactionsByWalletId (walletId) {
        this.transactions = _([
          { 'id': 1, 'from': 'channa@russia', 'to': 'you', 'amount': 313.33, 'date': '2017-07-19T17:36:25Z' },
          { 'id': 2, 'from': 'gibby@russia', 'to': 'you', 'amount': 291.95, 'date': '2017-05-05T16:30:27Z' },
          { 'id': 3, 'from': 'elmer@russia', 'to': 'you', 'amount': 189.05, 'date': '2018-04-19T15:49:41Z' },
          { 'id': 4, 'from': 'ezechiel@russia', 'to': 'you', 'amount': 71.87, 'date': '2018-01-30T18:08:31Z' },
          { 'id': 5, 'from': 'tadeas@russia', 'to': 'you', 'amount': 138.08, 'date': '2017-08-11T11:11:21Z' },
          { 'id': 6, 'from': 'merrielle@russia', 'to': 'you', 'amount': 442.48, 'date': '2017-05-12T04:09:59Z' },
          { 'id': 7, 'from': 'shell@russia', 'to': 'you', 'amount': 484.54, 'date': '2017-08-18T06:20:40Z' },
          { 'id': 8, 'from': 'yurik@russia', 'to': 'you', 'amount': 370.53, 'date': '2018-01-12T01:51:50Z' },
          { 'id': 9, 'from': 'pen@russia', 'to': 'you', 'amount': 149.01, 'date': '2018-02-19T07:07:40Z' },
          { 'id': 10, 'from': 'joly@russia', 'to': 'you', 'amount': 400.81, 'date': '2017-09-13T14:28:05Z' }
        ])
          .chain()
          .sampleSize(5)
          .map((d) => {
            d.date = moment(d.date).format('DD.MM.YYYY')
            return d
          })
          .value()
      }
    }
  }
</script>

<style lang="scss" scoped>
  @import "~@/styles/element-variables.scss";

  .transaction-table {
    &::before {
      content: none; // removes an el-table's border
    }

    /deep/ th {
      color: black;
      background: #c4c4c4;
    }

    /deep/ td {
      border: none;
    }
  }
</style>
