<template>
  <div class="wallet">
    {{ wallet.name }} {{ wallet.amount }}

    <el-tabs class="wallet__tabs" v-model="activeTabName">
      <el-tab-pane label="HISTORY" name="history">
        <transactions :transactions="transactions" />
      </el-tab-pane>

      <el-tab-pane label="SEND" name="send">
        <transfer-form
          ref="form"
          v-model="form"
          :maxDecimalDigits="maxDecimalDigits"
          @submit="onSubmit"
        ></transfer-form>
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<script>
  import _ from 'lodash'
  import Transactions from '@/components/Transactions'
  import TransferForm from '@/components/TransferForm'

  export default {
    name: 'wallets-page',

    components: {
      Transactions,
      TransferForm
    },

    data () {
      return {
        activeTabName: 'history',
        wallet: {},
        transactions: [],
        form: {},
        maxDecimalDigits: 0
      }
    },

    watch: {
      /**
       * React to params changes and reuse the same component
       * c.f. https://router.vuejs.org/en/essentials/dynamic-matching.html
       */
      '$route' (to, from) {
        // Reset the instance's data c.f. https://github.com/vuejs/vue/issues/702
        Object.assign(this.$data, this.$options.data())

        this.fetchWalletByWalletId(this.$route.params.walletId)
        this.fetchTransactionsByWalletId(this.$route.params.walletId)
        this.updateMaxDecimalDegits()
        this.$nextTick(() => this.$refs['form'].clearValidationMessage())
      }
    },

    created () {
      this.fetchWalletByWalletId(this.$route.params.walletId)
      this.fetchTransactionsByWalletId(this.$route.params.walletId)
      this.updateMaxDecimalDegits()
    },

    methods: {
      /**
       * TODO: This is dummy and wallets master data are hardcoded for now.
       * I guess it will be replaced with API call to fetch a wallet by walletId
       * and will perform dispatching an action to a store or the like.
       */
      fetchWalletByWalletId (walletId) {
        this.$store.dispatch('getAccountAssets')
          .then(() => {
            this.wallet = this.$store.getters.wallets
              .find((w) => (w.id === walletId))
          })
      },

      /**
       * TODO: This is dummy.
       * The dummy data was generated by https://mockaroo.com/
       */
      fetchTransactionsByWalletId (walletId) {
        this.$store.dispatch('getAccountTransactions')
          .then(() => {
            this.transactions = this.$store.getters.getTransfersByWalletId(walletId)
          })
      },

      /**
       * TODO: This is dummy. maxDecimalDigits is different for every asset
       */
      updateMaxDecimalDegits () {
        this.maxDecimalDigits = _.random(0, 5)
      },

      onSubmit () {
        alert(`send: ${JSON.stringify(this.form)}`)
      }
    }
  }
</script>

<style lang="scss" scoped>
  @import "~@/styles/element-variables.scss";

  .wallet {
    padding: 1rem 2rem;

    &__tabs {
      margin: 1rem 0;

      /deep/ .el-tabs__header {
        text-align: center;
      }

      /deep/ .el-tabs__nav {
        float: none;
        display: inline-block;
      }
    }
  }
</style>
